<?php
$a = 10;
$b = 5;

$hasilTambah = $a + $b;
$hasilKurang = $a - $b;
$hasilKali = $a * $b;
$hasilBagi = $a / $b;
$sisaBagi = $a % $b;
$pangkat = $a ** $b;
$hasilSama = $a == $b;
$hasilTidakSama = $a != $b;
$hasilLebihKecil = $a < $b;
$hasilLebihBesar = $a > $b;
$hasilLebihKecilSama = $a <= $b;
$hasilLebihBesarSama = $a >= $b;
$hasilAnd = $a && $b;
$hasilOr = $a || $b;
$hasilNotA = !$a;
$hasilNotB = !$b;
$a += $b;
$a -= $b;
$a *= $b;
$a /= $b;
$a %= $b;
$hasilIdentik = $a == $b;
$hasilTidakIdentik = $a !== $b;

echo "Hasil Tambah : {$hasilTambah} <br>";
echo "Hasil Kurang : {$hasilKurang} <br>";
echo "Hasil Kali : {$hasilKali} <br>";
echo "Hasil Bagi : {$hasilBagi} <br>";
echo "Hasil Sisa Bagi : {$sisaBagi} <br>";
echo "Hasil Pangkat : {$pangkat} <br>";
echo "Hasil sama : {$hasilSama}<br>";
echo "Hasil Tidak Sama : {$hasilTidakSama}<br>";
echo "Hasil Lebih Kecil : {$hasilLebihKecil}<br>";
echo "Hasil Lebih Besar : {$hasilLebihBesar}<br>";
echo "Hasil Lebih Kecil sama : {$hasilLebihKecilSama}<br>";
echo "Hasil Lebih Besar sama : {$hasilLebihBesarSama}<br>";
echo "Hasil And : {$hasilAnd} <br>";
echo "Hasil Or : {$hasilOr}<br>";
echo "Hasil Not A : {$hasilNotA} <br>";
echo "Hasil Not B : {$hasilNotB} <br>"; 
echo "Hasil Penugasan Penjumlahan : {$a}<br>";
echo "Hasil Penugasan Pengurangan : {$a}<br>";
echo "Hasil Penugasan Perkalian : {$a}<br>";
echo "Hasil Penugasan Pembagian : {$a}<br>";
echo "Hasil Penugasan Sisa Bagi : {$a}<br>";
echo "Hasil Identik : {$hasilIdentik} <br>";
echo "Hasil Tidak Identik : {$hasilTidakIdentik}<br>";
